# Generated by Django 6.1.1 on 2026-09-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0005_alter_designation_slug_alter_specialization_slug'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.CharField(choices=[('Running', 'Running'), ('Pending', 'Pending')], max_length=12)),
                ('appointment_types', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=12)),
                ('symptom', models.TextField()),
                ('cancel', models.BooleanField(default=False)),
                ('avaliable_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletime')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
