# Generated by Django 6.1.1 on 2026-09-22 15:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_fee_doctor_meetlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
